// <auto-generated />
using System;
using FIT_Api_Example.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIT_Api_Example.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountID");

                    b.ToTable("Account");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Account");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Actor", b =>
                {
                    b.Property<int>("ActorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorID");

                    b.ToTable("Actor");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.CinemaHall", b =>
                {
                    b.Property<int>("CinemaHallID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CinemaHallID"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CinemaHallID");

                    b.ToTable("CinemaHall");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            CityID = 1,
                            Name = "Banja Luka"
                        },
                        new
                        {
                            CityID = 2,
                            Name = "Bihać"
                        },
                        new
                        {
                            CityID = 3,
                            Name = "Bijeljina"
                        },
                        new
                        {
                            CityID = 4,
                            Name = "Bosnaska Krupa"
                        },
                        new
                        {
                            CityID = 5,
                            Name = "Cazin"
                        },
                        new
                        {
                            CityID = 6,
                            Name = "Čapljina"
                        },
                        new
                        {
                            CityID = 7,
                            Name = "Drventa"
                        },
                        new
                        {
                            CityID = 8,
                            Name = "Doboj"
                        },
                        new
                        {
                            CityID = 9,
                            Name = "Goražde"
                        },
                        new
                        {
                            CityID = 10,
                            Name = "Gračanica"
                        },
                        new
                        {
                            CityID = 11,
                            Name = "Gradačac"
                        },
                        new
                        {
                            CityID = 12,
                            Name = "Gradiška"
                        },
                        new
                        {
                            CityID = 13,
                            Name = "Konjic"
                        },
                        new
                        {
                            CityID = 14,
                            Name = "Laktaši"
                        },
                        new
                        {
                            CityID = 15,
                            Name = "Livno"
                        },
                        new
                        {
                            CityID = 16,
                            Name = "Lukavac"
                        },
                        new
                        {
                            CityID = 17,
                            Name = "Ljubuški"
                        },
                        new
                        {
                            CityID = 18,
                            Name = "Mostar"
                        },
                        new
                        {
                            CityID = 19,
                            Name = "Orašje"
                        },
                        new
                        {
                            CityID = 20,
                            Name = "Prijedor"
                        },
                        new
                        {
                            CityID = 21,
                            Name = "Prnjavor"
                        },
                        new
                        {
                            CityID = 22,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            CityID = 23,
                            Name = "Srebrenik"
                        },
                        new
                        {
                            CityID = 24,
                            Name = "Stolac"
                        },
                        new
                        {
                            CityID = 25,
                            Name = "Široki Brijeg"
                        },
                        new
                        {
                            CityID = 26,
                            Name = "Travnik"
                        },
                        new
                        {
                            CityID = 27,
                            Name = "Tuzla"
                        },
                        new
                        {
                            CityID = 28,
                            Name = "Visoko"
                        },
                        new
                        {
                            CityID = 29,
                            Name = "Zavidovići"
                        },
                        new
                        {
                            CityID = 30,
                            Name = "Zenica"
                        },
                        new
                        {
                            CityID = 31,
                            Name = "Zvornik"
                        },
                        new
                        {
                            CityID = 32,
                            Name = "Živinice"
                        },
                        new
                        {
                            CityID = 33,
                            Name = "Donji Vakuf"
                        },
                        new
                        {
                            CityID = 34,
                            Name = "Zavidovići"
                        });
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Director", b =>
                {
                    b.Property<int>("DirectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirectorID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirectorID");

                    b.ToTable("Director");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Gender", b =>
                {
                    b.Property<int>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderID");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            GenderID = 1,
                            Name = "Male"
                        },
                        new
                        {
                            GenderID = 2,
                            Name = "Fmale"
                        });
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            Name = "Action"
                        },
                        new
                        {
                            GenreID = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreID = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            GenreID = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreID = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            GenreID = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreID = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            GenreID = 8,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            GenreID = 9,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            GenreID = 10,
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreID = 11,
                            Name = "Crime"
                        },
                        new
                        {
                            GenreID = 12,
                            Name = "Historical"
                        },
                        new
                        {
                            GenreID = 13,
                            Name = "Superhero"
                        },
                        new
                        {
                            GenreID = 14,
                            Name = "Western"
                        },
                        new
                        {
                            GenreID = 15,
                            Name = "Musical"
                        },
                        new
                        {
                            GenreID = 16,
                            Name = "War"
                        },
                        new
                        {
                            GenreID = 17,
                            Name = "Biographical"
                        },
                        new
                        {
                            GenreID = 18,
                            Name = "Sports"
                        },
                        new
                        {
                            GenreID = 19,
                            Name = "Family"
                        },
                        new
                        {
                            GenreID = 20,
                            Name = "Animation"
                        },
                        new
                        {
                            GenreID = 21,
                            Name = "Documentary"
                        },
                        new
                        {
                            GenreID = 22,
                            Name = "Noir"
                        },
                        new
                        {
                            GenreID = 23,
                            Name = "Fantasy Adventure"
                        },
                        new
                        {
                            GenreID = 24,
                            Name = "Romantic Comedy"
                        },
                        new
                        {
                            GenreID = 25,
                            Name = "Psychological Thriller"
                        },
                        new
                        {
                            GenreID = 26,
                            Name = "Slasher"
                        },
                        new
                        {
                            GenreID = 27,
                            Name = "Parody"
                        },
                        new
                        {
                            GenreID = 28,
                            Name = "Post-Apocalyptic"
                        },
                        new
                        {
                            GenreID = 29,
                            Name = "Found Footage"
                        },
                        new
                        {
                            GenreID = 30,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            GenreID = 31,
                            Name = "Spy"
                        },
                        new
                        {
                            GenreID = 32,
                            Name = "Disaster"
                        },
                        new
                        {
                            GenreID = 33,
                            Name = "Dark Comedy"
                        },
                        new
                        {
                            GenreID = 34,
                            Name = "Teen"
                        },
                        new
                        {
                            GenreID = 35,
                            Name = "Gothic Horror"
                        },
                        new
                        {
                            GenreID = 36,
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            GenreID = 37,
                            Name = "Steampunk"
                        },
                        new
                        {
                            GenreID = 38,
                            Name = "Space Opera"
                        },
                        new
                        {
                            GenreID = 39,
                            Name = "Time Travel"
                        });
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerID");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieID"), 1L, 1);

                    b.Property<int>("DirectorID")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<byte[]>("Poster")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ProductionHouseID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieID");

                    b.HasIndex("DirectorID");

                    b.HasIndex("ProductionHouseID");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieActorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieActorID"), 1L, 1);

                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("MovieActorID");

                    b.HasIndex("ActorID");

                    b.HasIndex("MovieID");

                    b.ToTable("MovieActor");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieGenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieGenreID"), 1L, 1);

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.HasKey("MovieGenreID");

                    b.HasIndex("GenreID");

                    b.HasIndex("MovieID");

                    b.ToTable("MovieGenre");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.MovieType", b =>
                {
                    b.Property<int>("MovieTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieTypeID"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieTypeID");

                    b.ToTable("MovieType");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.ProductionHouse", b =>
                {
                    b.Property<int>("ProductionHouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionHouseID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductionHouseID");

                    b.ToTable("ProductionHouse");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Projection", b =>
                {
                    b.Property<int>("ProjectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectionID"), 1L, 1);

                    b.Property<int>("CinemaHallID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("MovieTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectionID");

                    b.HasIndex("CinemaHallID");

                    b.HasIndex("MovieID");

                    b.HasIndex("MovieTypeID");

                    b.ToTable("Projection");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("MovieID");

                    b.HasIndex("UserID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Seat", b =>
                {
                    b.Property<int>("SeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatID"), 1L, 1);

                    b.Property<int>("CinemaHallID")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("SeatID");

                    b.HasIndex("CinemaHallID");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectionID")
                        .HasColumnType("int");

                    b.Property<int>("SeatID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TicketID");

                    b.HasIndex("ProjectionID");

                    b.HasIndex("SeatID");

                    b.HasIndex("UserID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Administrator", b =>
                {
                    b.HasBaseType("FIT_Api_Example.Data.Models.Account");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.User", b =>
                {
                    b.HasBaseType("FIT_Api_Example.Data.Models.Account");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CityID");

                    b.HasIndex("GenderID");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Movie", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.ProductionHouse", "ProductionHouse")
                        .WithMany()
                        .HasForeignKey("ProductionHouseID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("ProductionHouse");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.MovieActor", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.MovieGenre", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Order", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Product", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Projection", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.CinemaHall", "CinemaHall")
                        .WithMany()
                        .HasForeignKey("CinemaHallID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.MovieType", "MovieType")
                        .WithMany()
                        .HasForeignKey("MovieTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CinemaHall");

                    b.Navigation("Movie");

                    b.Navigation("MovieType");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Review", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Seat", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.CinemaHall", "CinemaHall")
                        .WithMany()
                        .HasForeignKey("CinemaHallID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CinemaHall");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.Ticket", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.Projection", "Projection")
                        .WithMany()
                        .HasForeignKey("ProjectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Projection");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIT_Api_Example.Data.Models.User", b =>
                {
                    b.HasOne("FIT_Api_Example.Data.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FIT_Api_Example.Data.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
